### PR TITLE
noob proof sql connection string

### PR DESCRIPTION
**Pull request by juddisjudd**

### CODE REVIEW

**Comment by DokaDoka** [comment]
I guess there's no harm in this, but I'm wondering has this ever been an issue? I have yet to see it
Another option to consider would be to have both connection string formats but have one commented out by default seeing as people tend to struggle with one or the other

**Comment by juddisjudd** [comment]
> I guess there's no harm in this, but I'm wondering has this ever been an issue? I have yet to see it Another option to consider would be to have both connection string formats but have one commented out by default seeing as people tend to struggle with one or the other

What I suggested has seemed to lead to less people having issues. Sure it's probably on the user end but using that string less people complained about db connection issues.

**Comment by DokaDoka** [comment]
@nightowlsrp I'd rather have the old format there as a secondary string, change to that and I'll be able to merge

**Comment by DokaDoka** [comment]
I opted to commit this myself as I am restructuring the repo
But I added you as a Co-author ❤️

**Pull request closed without merging**
